### ISSUE TITLE
Getting Error: "We can't connect to the selected Plex Media Server"

### ISSUE THREAD

**Issue by def324** [aiguestdj/plex-extension#1]
I tried to install this via docker compose (plex also running in docker compose). I get the UI to load and am able to log into Plex, however when selecting the plex server I'm getting: "We can't connect to the selected Plex Media Server".

I verified from within the docker container that connectivity to plex is working by running wget towards the plex URL. Any idea what might cause this?

This looks like a really promising project, looking forward to getting it running soon :)

**Comment by jjdenhertog** [comment]
@def324 it is probably an authorization issue. I have mostly tested this setup on a local environment. I just pushed an update that allows to re-authenticate Plex. Which might help.

I do need some more info in order to find the root cause. So to help, let me explain how it works:

**Authentication**
When you're authenticated you will get a token which is stored in a JSON file called "plex.json" and stored in the config folder. This token is used to make API calls.

**Visit: http://[ip]:9020/api/resources**
This page should show all the connections that you have.  This will include a server that has the property "local" set to "true". That is the scenario I've tested it mostly on - local setups.

**Validating the connection**
To test if the combination with your token and the selected server works you can concatenate the following data:
- Server IP address: e.g. http://192.168.50.130:32400
- Token: e.g. 1asHas_39saa
- API call: /hubs/search?query=x

 http://192.168.50.130:32400/hubs/search?query=x&X-Plex-Token=1asHas_39saa

When visiting that URL it should display the search results. If something went wrong while authenticating you will get an error on that page (401 Unauthorized).

====
Questions:
- What happens when you visit the API call as listed above?
- Do you have local music added to your plex or streaming only?
- Are you able to locate a API token using this approach: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
-- And if so: Does using that token result into a better result when using the /hubs/search API call?

**Comment by def324** [comment]
I did some testing and the issues seems to be related to HTTPS. When I have my plex settings set to Secure connections: 
"Preferred", rather than "Required", I can get it to work. In my setup I would very much prefer to stick to HTTPS required, however that means when connecting to an IP likely the certificate checks fail (I believe done inside the axios library that you use). An option to turn the certificate checks off would work for my use case.

**Comment by jjdenhertog** [comment]
@def324 I've updated the code. When you update your docker to the latest version (1.0.48) it will probably worked. I have tested it with a similar setup (setting "Secure connection" to "required"). 

Could you check and confirm?

**Comment by def324** [comment]
Thanks, that fixed it!
